language: ruby
cache: bundler
sudo: false

matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
  include:
    - rvm: 2.1.5
    - rvm: jruby-1.7.18
      env: JRUBY_OPTS=--2.0
      jdk: openjdk7
    - rvm: 2.2.0
    - rvm: jruby-head
      jdk: openjdk7
      
script: bundle exec rake spec
